### ISSUE TITLE
Pico-Pixel says "Unknown Format" for valid KTX cubemap

### ISSUE THREAD

**Issue by msc-** [inalogic/pico-pixel-public#21]
When opening https://github.com/SaschaWillems/Vulkan/raw/master/data/textures/cubemap_vulkan.ktx, PP reports unknown format. The file is loaded successfully by GL & Vukan applications using gli.

**Comment by jaytaoko** [comment]
Thank you for reporting. I am looking into the issue.

**Comment by jaytaoko** [comment]
PicoPixel 0.6.12 has been release with a fix for this issue. Please report here if the issue is still happening.

Regards!

**Comment by msc-** [comment]
It's fixed. Thanks.
