### ISSUE TITLE
web site down?

### ISSUE THREAD

**Issue by cdwfs** [inalogic/pico-pixel-public#27]
I notice that pixelandpolygon.com is no more -- has this project been abandoned, or is it just web hosting issues?

**Comment by jaytaoko** [comment]
Thank you for your interest. The project is still on. Just hasn't been updated in a while. The website should be on now.
Get the latest version from here: 
https://github.com/inalogic/pico-pixel-public/blob/master/pre-release/PicoPixel-0.7.00-x64.zip

Jay

**Comment by cdwfs** [comment]
Great news, thanks! I love this tool; please don't disappear :)
