### ISSUE TITLE
Program stops when try to open ktx image

### ISSUE THREAD

**Issue by SC5Shout** [inalogic/pico-pixel-public#28]
I'd like to open "opengl superbible 7th" book example textures http://www.openglsuperbible.com/example-code/ **_media archive_** hyperlink, but whatever I open it closes the program or returns unknown format.

**Comment by jaytaoko** [comment]
Thank you for reporting. There is indeed a problem with ktx images.
I am working on a fix...

**Comment by SC5Shout** [comment]
Lemme know when you fix it.

**Comment by jaytaoko** [comment]
After a closer look, the ktx files from the source archive were badly written. They missed important information as specified in the KTX file format: https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/

The main issues are:
* Missing _imageSize_ data
* Incorrect alignment of image data in the files

Without these, the image would load load incorrectly or crash PicoPixel.

I have corrected the archive files and placed a copy here: [Modified KTX files](https://github.com/inalogic/pico-pixel-public/blob/master/misc/opengl-superbible-ktx-textures-modified.zip)

I also recommend you use the version of pico pixel provided here:
[PicoPixel 0.7.1](https://github.com/inalogic/pico-pixel-public/blob/master/pre-release/PicoPixel-0.7.01-x64.zip)

Please try it and let me know how it goes.

**Comment by SC5Shout** [comment]
Now it works almost perfectly, some images are flipped and some do not, guess it is something inside their code, does not matter. How did you look inside the files?

**Comment by jaytaoko** [comment]
I also noticed the inverted image. I guess this is another issue with how the files were created.

I first thought the issue was with PicoPixel. But then I tested [Khronos KTX test images](https://github.com/KhronosGroup/KTX-Software/tree/master/tests/testimages) and they were working correctly in PicoPixel.

So then I took a look at the KTX image loader I wrote for PicoPixel and noticed incorrect and bizarre values in some fields. The KTX file format specification was helpful to pinpoint what was missing in the files.

Thank you for reporting!

**Comment by SC5Shout** [comment]
Thank you for answer

**Comment by SC5Shout** [comment]
Actually, I've got one more question. How did you fixed files from the book? I mean, I know you had to add `imageSize` and fix `alignment`, but that needs to get into texture code somehow. What did you use to get the texture code the way to change it?

**Comment by jaytaoko** [comment]
I modified my KTX loader such that as it read data from a ktx file, it would write the same data in a new file, add the missing information and correct the data alignment where necessary. It was a quick hack mostly.
My personal interest in doing it, is that I now have an additional set of KTX files I can use for tests
:)

**Comment by SC5Shout** [comment]
Oh, nice, thank you.
