### ISSUE TITLE
Unknown format when opening ktx file.

### ISSUE THREAD

**Issue by GlowingUmbreon** [inalogic/pico-pixel-public#32]
Exacly as title says, happens with any of my ktx file's I attempt to open, but appears to work fine with the examples here: https://github.com/inalogic/pico-pixel-public/blob/master/misc/opengl-superbible-ktx-textures-modified.zip

**Comment by jaytaoko** [comment]
Thank you for your feedback!
An issue with a set of ktx textures was previously reported in https://github.com/inalogic/pico-pixel-public/issues/28. In my opinion, the original files were broken. Fortunately they weren't beyond repair. So I placed a copy of the corrected files in https://github.com/inalogic/pico-pixel-public/blob/master/misc/opengl-superbible-ktx-textures-modified.zip
Are you using the original set of ktx textures from opengl superbible or a different set of textures?

Feel free to provide one of your failing files, and I will take a look.
