### ISSUE TITLE
Support QOI image file format

### ISSUE THREAD

**Issue by corporateshark** [inalogic/pico-pixel-public#34]
Losslessly compresses RGB and RGBA images to a similar size of PNG, while offering a 20x-50x speedup in compression and 3x-4x speedup in decompression.

https://github.com/phoboslab/qoi
https://github.com/phoboslab/qoi/issues/37

**Comment by jaytaoko** [comment]
Thank you for the feedback! I will look into the format.
I will let you know when support is ready.

**Comment by jaytaoko** [comment]
Support for QOI was easy to add! I will release a new version of Pico Pixel in a few days.

![qoi-support](https://user-images.githubusercontent.com/1514772/147716974-44c7f3c7-2d68-467f-8526-a3b110a68d5c.png)

**Comment by jaytaoko** [comment]
Support for QOI files is available: https://pixelandpolygon.com/picopixel-download
